### ISSUE TITLE
[SUGGEST]: Add CREATE/trains support for Portals

### ISSUE THREAD

**Issue by SrRapero720** [TheCosmicNebula/CosmosPortals#6]
Probably is not the purpose or how is coded the mod. But something cool for test adding is the support for create contraptions trains
Its kinda be interesting have a full cross-dimension utility for trains and `other dimension mods` or custom `mod` dimensions...

![image](https://user-images.githubusercontent.com/29090346/194782995-0a3f40cf-8bab-40b4-8169-a56811551507.png)

**Comment by TheCosmicNebula** [comment]
Currently I don't think this would be possible. 1 car maybe possible if Create considers Trains as entities, but the links between cars would be destroyed upon travel.

**Comment by JDtheHutt** [comment]
This is likely possible with Immersive Portals, as I have made vanilla rail systems going back and forth through them both within same dimension and between dimensions.  But that only works I believe due to the two sides having their chunks loaded and rendered with the portal being treated as a seamless transition point.  If Immersive Portals could work with Cosmos Portals then that would let you have the desired effect, but I have no idea if that is possible.  Immersive Portals also does have some issues working with other mods due to the way it has them working so it can be a problem in a larger modpack.

EDIT: Immersive Portals are also able to be bi-directional, which differs from Cosmos in its operation.

**Comment by SrRapero720** [comment]
Inmersive portals is a extension of nether portals, you cant use these portal cross-dimensions excepting nether. Cosmic is a mod usable in custom dimensions, thats the pruporse of the integration with create mod (create mod cant move into other dimensions), the only cross-dimension mod in 1.18.2 its cosmo portals

**Comment by JDtheHutt** [comment]
> Inmersive portals is a extension of nether portals, you cant use these portal cross-dimensions excepting nether. Cosmic is a mod usable in custom dimensions, thats the pruporse of the integration with create mod (create mod cant move into other dimensions), the only cross-dimension mod in 1.18.2 its cosmo portals

Since when? I have used Immersive Portals for ages on Fabric and it always had full operation within the same dimension and across all dimensions, though some mods are incompatible.  I just chucked up a new Forge 1.18.2 instance with Immersive Portals and a bunch of random dimension mods I haven't even used before and I was able to generate Immersive Portals between the Overworld, Nether, End, and the other modded dimensions with no issue whatsoever and it worked flawlessly.

**Comment by SrRapero720** [comment]
I've searching and create contraptions are considered entities (carriage)
Also teleport system its individual over normal teleporting. using fancy lines to trace train routes and runs teleport when a "valid nether portal" its detected

all comes from `package com.simibubi.create.content.logistics.trains.entity;` into [`tickContraption`](https://github.com/Creators-of-Create/Create/blob/8d89080bc065d54d23c55adeede17f6dc066dafd/src/main/java/com/simibubi/create/content/logistics/trains/entity/CarriageContraptionEntity.java#L208)

Theorically the most viable method to implement that its add a new item to "connect" a trainrail (from an y dim) into portal and  make portal a teleport rail (From other rail)...  i am not a good modder so probably i am saying silly things.

**Comment by SrRapero720** [comment]
hi again, long time i arrive this repo.
i was interested to make a PR adding Create compatibility (tweaking some stuff) btw i see the source code of 1.18.2 isn't avairable, just for 1.18 without gradle filles (or any other important stuff). is branch outdated or is just a private repository? because mod was updated 8 months ago and last repo update was 1 year ago.

so if was possible get source code to make a PR would be asome :) (if was possible)

**Comment by TheCosmicNebula** [comment]
Hi, I have been lacking on updating the repo I will be fair, I will upload the repo as soon as I can.

**Comment by SrRapero720** [comment]
Ok, I'll wait then :)
